### ISSUE TITLE
修改nvdsparsebbox_Yolo.cpp参数

### ISSUE THREAD

**Issue by yin-qiyu** [rscgg37248/DeepStream6.0_Yolov5-6.0#6]
当我想部署自己训练的模型，是否需要在nvdsparsebbox_Yolo.cpp中修改static const int NUM_CLASSES_YOLO 的数量，在您的库文件中没有找到可以修改类型的地方，还是说直接生成.so文件就可以了呢，谢谢

**Comment by Fly-Pluche** [comment]
> 当我想部署自己训练的模型，是否需要在nvdsparsebbox_Yolo.cpp中修改static const int NUM_CLASSES_YOLO 的数量，在您的库文件中没有找到可以修改类型的地方，还是说直接生成.so文件就可以了呢，谢谢


请问你是怎么解决的呢？

**Comment by yin-qiyu** [comment]
直接生成.so文件放到ds文件夹就好了

**Comment by Fly-Pluche** [comment]
谢谢，主要是我在运行deepstream-app的时候遇到Num classes mismatch的问题

**Comment by yin-qiyu** [comment]
这个库的cpp貌似和别的库有些不一样  我没有修改参数直接生成的so文件也可以部署自己的模型
